In [2]:
import numpy as np  
import pandas as pd

baseline = pd.read_csv('C:/Users/dyros/Desktop/dummy_ws/baseline.csv')
euler = pd.read_csv('C:/Users/dyros/Desktop/dummy_ws/euler.csv')
NN = pd.read_csv('C:/Users/dyros/Desktop/dummy_ws/NN.csv')

In [7]:
print(baseline.shape,euler.shape,NN.shape)

(1235, 10) (1229, 201) (1224, 10)

In [8]:
baseline.head(5)

,%time,field.layout.data_offset,field.data0,field.data1,field.data2,field.data3,field.data4,field.data5,field.data6,field.data7
0,1755834413517681900,0,-0.5,-0.144548,-0.196286,-0.143485,0.859776,0.261408,0.274151,0.243965
1,1755834413539608500,0,-0.5,-0.144548,-0.196286,-0.143485,0.859776,0.261408,0.274151,0.243965
2,1755834413561641300,0,-0.5,-0.144548,-0.196286,-0.143485,0.859776,0.261408,0.274151,0.243965
3,1755834413584352600,0,-0.5,-0.144548,-0.196286,-0.143485,0.859776,0.261408,0.274151,0.243965
4,1755834413605176200,0,-0.5,-0.144548,-0.196286,-0.143485,0.859776,0.261408,0.274151,0.243965

In [9]:
euler.head(5)

,%time,field.header.seq,field.header.stamp,field.header.frame_id,field.pose_array.header.seq,field.pose_array.header.stamp,field.pose_array.header.frame_id,field.pose_array.poses0.position.x,field.pose_array.poses0.position.y,field.pose_array.poses0.position.z,...,field.angles2,field.angles3,field.angles4,field.angles5,field.angles6,field.angles7,field.angles8,field.angles9,field.angles10,field.trigger_flag
0,1755834413627344100,2192,1755834413625561700,hmd_frame,0,1755834413625561700,hmd_frame,-0.002292,-0.010014,-0.462709,...,-11.453092,-12.850790,68.682426,-17.768175,-22.005074,-14.157873,-0.231144,0.022336,-0.214613,0
1,1755834413648033900,2193,1755834413646259700,hmd_frame,0,1755834413646259700,hmd_frame,-0.002321,-0.009924,-0.462714,...,-11.454185,-12.850993,68.682320,-17.765047,-22.003298,-14.157924,-0.231422,0.022248,-0.214633,0
2,1755834413669592000,2194,1755834413667723400,hmd_frame,0,1755834413667723400,hmd_frame,-0.002362,-0.009868,-0.462751,...,-11.455170,-12.851176,68.682228,-17.763716,-22.001699,-14.157970,-0.231487,0.022077,-0.214666,0
3,1755834413689861500,2195,1755834413688016000,hmd_frame,0,1755834413688016000,hmd_frame,-0.002267,-0.009960,-0.462767,...,-11.456057,-12.851340,68.682144,-17.762518,-22.000261,-14.158012,-0.231372,0.022712,-0.214465,0
4,1755834413711784300,2196,1755834413709654000,hmd_frame,0,1755834413709654000,hmd_frame,-0.002299,-0.009865,-0.462777,...,-11.456854,-12.851487,68.676773,-17.761440,-21.998968,-14.158051,-0.231638,0.022254,-0.214521,0